### ISSUE TITLE
StyleCI

### ISSUE THREAD

**Issue by JayBizzle** [laravel-notification-channels/ionic-push-notifications#19]
@freekmurze @themsaid any idea why this repo is no longer linked to StyleCI. The badge in the readme isn't working and this link no longer works https://styleci.io/repos/65854274

Cheers

M

**Comment by JayBizzle** [comment]
Seems to be the same for most channel repos

**Comment by JayBizzle** [comment]
Nudge @freekmurze

**Comment by freekmurze** [comment]
There was an issue at StyleCI that caused the repo to be removed from their service.

I've re-added it, so your badge should work again.
