### ISSUE TITLE
Please mention sendTo() in the readme

### ISSUE THREAD

**Issue by fureszk** [laravel-notification-channels/ionic-push-notifications#27]
I've spent 30 minutes figuring out why my code does not work, and all I had to do is use sendTo('user_ids').

**Comment by JayBizzle** [comment]
Perhaps you could edit the `readme` with what you think needs adding and submit it as a PR.

That'd be great 👍

**Comment by fureszk** [comment]
You are right, I'm sorry. Submitted my first PR ever. :)

**Comment by JayBizzle** [comment]
Good work, congrats on your first PR 👍
