### ISSUE TITLE
Android add Icon

### ISSUE THREAD

**Issue by iparrabb** [laravel-notification-channels/ionic-push-notifications#29]
Hi,

I'm trying to send notifications to Ionic with a custom Icon but doesn't work's, can you add an example of usage please?.

My code.

```javascript
return IonicPushMessage::create('development')
	    ->androidIcon('//mydomain.com/592d4681a24b6.png')
            ->androidTitle($this->notification['title'])
            ->androidMessage($this->notification['message']);
```

**Comment by JayBizzle** [comment]
Did you solve this?

**Comment by uno-de-piera** [comment]
Yeah, I was able to solve this adding the icon like a resource but not like an url.

```php
return $notification
	    ->androidIcon('ic_stat_airplanemode_active')
            ->androidTitle($this->notification['title'])
            ->androidMessage($this->notification['message']);
```

The resource has been generated [using this platform](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html) and works fine.

**Comment by iparrabb** [comment]
Yeah, I was able to solve this adding the icon like a resource but not like an url.

```php
return $notification
	    ->androidIcon('ic_stat_airplanemode_active')
            ->androidTitle($this->notification['title'])
            ->androidMessage($this->notification['message']);
```

The resource has been generated [using this platform](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html) and works fine.
