### ISSUE TITLE
Set additionalData

### ISSUE THREAD

**Issue by iparrabb** [laravel-notification-channels/ionic-push-notifications#30]
Hi,

How I can set foreground and coldstart into additionalData?, this package need more documentation with examples please.

Can you add a full example please?

<img width="485" alt="captura de pantalla 2017-06-29 a las 15 05 31" src="https://user-images.githubusercontent.com/13960435/27688912-9152811e-5cdc-11e7-98a2-9ae5b255801b.png">

**Comment by JayBizzle** [comment]
All this library does is wrap the Ionic API, so your best to read their docs http://legacy.docs.ionic.io/v2.0.0-beta/docs/push-sending-push#section-basic-api-usage

**Comment by iparrabb** [comment]
Thanks for your quick reply,

I have an example working outside Ionic box, only with firebase.

```php
$msg = [
    'body' 	=> $notification_request->message,
    'title'	=> $notification_request->title,
    'icon'	=> 'ic_stat_airplanemode_active',
    'notId' => $not->id,
    "content-available" => "1"
];
```

Is mandatory that I can set the parameter content-available, otherwise it does not work properly.

I can see into IonicPushMessage the avaliable fields for Android.

```php
public function allowedAndroidOptions()
{
    return [
        'collapse_key',
        'content_available',
        'data',
        'delay_while_idle',
        'icon',
        'icon_color',
        'message',
        'priority',
        'sound',
        'tag',
        'time_to_live',
        'title'
    ];
}
```

The problem is that I build the request with the next code and it does not work properly.

```php
return IonicPushMessage::create('my-security-profile')
       ->title('Your title')
       ->message('Your message')
       ->androidContentAvailable("1")//here is the problem, contentAvailable is not working
       ->sound('ping.aiff')
       ->payload(['foo' => 'bar']);
```

Thanks for your time.

**Comment by JayBizzle** [comment]
I think the problem is that the `content-available` key should be hyphenated whereas tis package is sending it snake cased like this `content_available`

If you could test and send a PR, that would be great, as i don't currently have any android devices to test on.

Thanks
