### ISSUE TITLE
How to implement in IONIC 2

### ISSUE THREAD

**Issue by satriantorobimo** [laravel-notification-channels/ionic-push-notifications#33]
Hello Mark Beech,

Im Bimo from Indonesia. I want to ask about this topic. Im trying to implement your github to my project, but my problem is how to configure in ionic 2? Can you help me?

Thankyou
GBU

**Comment by JayBizzle** [comment]
I haven't used Ionic 2.

Also, as of February 1, 2018, Ionic will no longer provide Push and Auth services, so if you are looking at implementing push in any of your apps right now, you should be looking at alternative solutions.

Source https://blog.ionic.io/sunsetting-ionic-cloud-push-and-auth/
